[project]
name = "pytoon"
version = "1.0.0"
authors = [
  { name="SanyIS" },
]
description = "A package to interact with Toonio.RU"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["pytoon"]

[project.dependencies]
numpy = "*"
pillow = "*"
requests = "*"
